# Generated by Django 3.2.6 on 2021-09-13 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=50)),
                ('archetype', models.CharField(max_length=50)),
                ('TCGP_price', models.FloatField()),
                ('ban_status', models.CharField(choices=[('B', 'Banned'), ('L', 'Limited'), ('S', 'Semi-Limited'), ('U', 'Unlimited')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spell_Trap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.card')),
            ],
        ),
        migrations.CreateModel(
            name='Pendulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atk', models.IntegerField()),
                ('df', models.IntegerField()),
                ('desc', models.TextField()),
                ('attr', models.CharField(max_length=10)),
                ('level', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.card')),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atk', models.IntegerField()),
                ('df', models.IntegerField()),
                ('desc', models.TextField()),
                ('attr', models.CharField(max_length=10)),
                ('level', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.card')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atk', models.IntegerField()),
                ('desc', models.TextField()),
                ('attr', models.CharField(max_length=10)),
                ('linkval', models.IntegerField()),
                ('linkmarkers', models.CharField(choices=[('T', 'Top'), ('TL', 'Top-Left'), ('TR', 'Top-Right'), ('L', 'Left'), ('R', 'Right'), ('B', 'Bottom'), ('BL', 'Bottom-Left'), ('BR', 'Bottom-Right')], max_length=2)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.deck')),
            ],
        ),
    ]
