# Generated by Django 3.2.6 on 2021-09-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck_card',
            old_name='amount',
            new_name='main_amount',
        ),
        migrations.AddField(
            model_name='deck_card',
            name='side_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
