# Generated by Django 3.2.6 on 2021-09-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20210914_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
