# Generated by Django 3.2.6 on 2021-09-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_rename_links_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='linkmarkers',
            field=models.CharField(max_length=20),
        ),
    ]
